# Rest API's listen address
api_addr: :5552
web_addr: http://frontend:3000

# Postgres' database connection address
database: postgres://postgres:postgres@postgres:5432/ticketer

# Use something like this for it: "pwgen -yns 32 1"
jwt_key: .9zvx5S+"Sompb!6be>2c%V(syEk2rSJ

# Application's hostname
host: "ticketer.haashemi.dev"
