-- +goose Up
create table if not exists movies (
    id              int8 primary key generated by default as identity   ,
    name            text            not null    unique                  ,
    movie_time      int2            not null                            ,
    genres          text[]          not null                            ,
    actresses       text[]                                              ,
    description     varchar(512)                                        ,
    from_date       date            not null                            ,
    to_date         date            not null                            ,
    premiere_time   timetz          not null
);

-- +goose Down
drop table if exists movies;
