-- +goose Up
create table if not exists users (
    id          int8 primary key generated by default as identity   ,
    full_name   text        not null                                ,
    email       text        not null    unique                      ,
    password    text        not null                                ,
    is_admin    boolean     not null    default false               ,

    constraint users_email_validation       check (email    ~*'^(?:[a-z0-9!#$%&''*+=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$')
);

-- +goose Down
drop table if exists users;
