// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	MovieTime        int16              `json:"movieTime"`
	Genres           []string           `json:"genres"`
	PremiereTime     pgtype.Timestamptz `json:"premiereTime"`
	PremiereFromDate pgtype.Date        `json:"premiereFromDate"`
	PremiereToDate   pgtype.Date        `json:"premiereToDate"`
}

type Seat struct {
	ID         int64 `json:"id"`
	TicketID   int64 `json:"ticketId"`
	SeatNumber int16 `json:"seatNumber"`
}

type Ticket struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"userId"`
	MovieID      int64              `json:"movieId"`
	ReservedAt   pgtype.Timestamptz `json:"reservedAt"`
	PremiereDate pgtype.Date        `json:"premiereDate"`
	PremiereTime pgtype.Timestamptz `json:"premiereTime"`
}

type User struct {
	ID       int64  `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
